/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0e0e10',
        surface: '#0e0e10',
        'surface-dim': '#0e0e10',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131316',
        'surface-container': '#19191c',
        'surface-container-high': '#1f1f22',
        'surface-container-highest': '#262529',
        'surface-bright': '#2c2c2f',
        'surface-variant': '#262529',
        'on-background': '#fffbfe',
        'on-surface': '#fffbfe',
        'on-surface-variant': '#adaaad',
        primary: '#ff7cf5',
        'on-primary': '#580058',
        'primary-container': '#ff5af9',
        'primary-dim': '#ff51fa',
        secondary: '#00eefc',
        'on-secondary': '#005359',
        'secondary-container': '#006970',
        'secondary-dim': '#00deec',
        tertiary: '#cc7aff',
        'on-tertiary': '#360055',
        'tertiary-container': '#aa19f9',
        outline: '#767578',
        'outline-variant': '#48474a',
        'surface-tint': '#ff7cf5',
        error: '#ff6e84',
        'error-container': '#a70138',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      boxShadow: {
        'neon-pink': '0 0 20px rgba(255,124,245,0.35)',
        'neon-cyan': '0 0 20px rgba(0,238,252,0.35)',
        'neon-pink-lg': '0 0 40px rgba(255,124,245,0.25)',
      },
    },
  },
  plugins: [],
}
